data_dir: "data"
sitemap:
  relative_dir: "xml"
  types: ["stations"]
  # overwrite: true
location:
  use_sitemap: False
  relative_dir: "json_results"
  location_type: "STATION"
  use_api: False
  chunk_size: 100
  min_seconds_between_requests: 2
mappings:
  relative_dir: "json_mappings"
  key: "name"
